In [1]:
import numpy as np

In [2]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
m1 = np.arange(16).reshape(4,4)

In [6]:
np.arange(16,32).reshape(4,4)

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [7]:
m2 = np.arange(16,32).reshape(4,4)

In [8]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
m1.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [10]:
m1 * m2

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [11]:
m1 + m2

array([[16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [12]:
m1 - m2

array([[-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16]])

In [14]:
m3 = m1.dot(m2)

In [15]:
m3

array([[ 152,  158,  164,  170],
       [ 504,  526,  548,  570],
       [ 856,  894,  932,  970],
       [1208, 1262, 1316, 1370]])

In [16]:
m3.ravel()

array([ 152,  158,  164,  170,  504,  526,  548,  570,  856,  894,  932,
        970, 1208, 1262, 1316, 1370])

In [17]:
m3.ravel().reshape(2,8)

array([[ 152,  158,  164,  170,  504,  526,  548,  570],
       [ 856,  894,  932,  970, 1208, 1262, 1316, 1370]])

In [21]:
np.random.normal(50,3,1000)

array([45.0000093 , 43.65329909, 49.26524127, 48.35015822, 50.95320427,
       47.72796035, 46.98877496, 52.97682098, 51.76551881, 52.92951337,
       51.7247612 , 43.82257642, 46.7022079 , 48.91109567, 51.72976387,
       49.05450031, 49.97081374, 54.27918907, 45.49801589, 49.09896033,
       49.21943023, 54.28222222, 53.05423087, 54.12767277, 48.90692995,
       49.46050967, 45.68660657, 45.4000316 , 48.671494  , 51.64060856,
       47.2106716 , 50.38225777, 49.77887855, 49.43227284, 51.33526084,
       47.13853271, 50.16018611, 47.15742368, 50.45517389, 46.1147423 ,
       52.26594475, 51.45057076, 49.56010747, 51.72710684, 54.86478652,
       51.40517579, 53.43520193, 56.34404649, 48.04803411, 51.29769814,
       52.0522706 , 49.87252692, 50.80963531, 49.8731856 , 49.20298068,
       47.64949002, 51.14385522, 51.72969766, 53.12979367, 50.69633735,
       50.92641415, 53.78359775, 51.96715363, 50.21277039, 48.76026992,
       50.82210098, 49.54079813, 43.95122299, 50.41020499, 47.35